// Row shapes for the CRM backend added in 0003_crm_backend.sql.
//
// These live outside integrations/supabase/types.ts on purpose: that file is
// machine-generated by Lovable and gets overwritten, so hand-written tables
// belong here instead.

export interface CrmCustomerRow {
  id: string;
  name: string;
  phone: string;
  wa_account: string | null;
  stage: string;
  owner: string | null;
  handler: string | null;
  temp: string | null;
  temp_reason: string | null;
  labels: string[];
  last_message: string | null;
  last_activity_at: string | null;
  last_action_at: string | null;
  next_action: string | null;
  next_action_at: string | null;
  journey: Record<string, string>;
  qualified_at: string | null;
  escalated: boolean;
  closed_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmEventRow {
  id: string;
  customer_id: string;
  at: string;
  actor: string;
  label: string;
  detail: string | null;
  step_key: string | null;
  module: string | null;
  changes: { field: string; from: string; to: string }[];
  created_at: string;
}

export type CommitmentState = "open" | "kept" | "missed" | "moved";

export interface CrmCommitmentRow {
  id: string;
  customer_id: string;
  promised_by: string;
  promised_at: string;
  due_at: string;
  window_id: string | null;
  steps: string[];
  note: string | null;
  state: CommitmentState;
  settled_at: string | null;
  settled_by: string | null;
  miss_reason: string | null;
  moved_from: string | null;
  source: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmWorkClaimRow {
  id: string;
  customer_id: string;
  operator_id: string;
  operator_name: string;
  module: string;
  claimed_at: string;
  expires_at: string;
  released_at: string | null;
  release_reason: string | null;
}

/** What every write returns, so callers can degrade instead of throwing. */
export interface WriteResult {
  ok: boolean;
  error?: string;
}
